In [1]:
import pandas as pd
import numpy as np

In [15]:
path = 'bea-tahfidz.xlsx'
bea_tahfidz = pd.read_excel(path)

In [16]:
bea_tahfidz.head()

ipk  bea_lain  sktm  hafalan  prestasi  status
0    1         0     1        1         1       1
1    1         0     0        1         0       1
2    1         0     0        2         1       1
3    1         0     0        2         1       1
4    1         0     0        2         1       1

In [17]:
bea_tahfidz.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 17 entries, 0 to 16
Data columns (total 6 columns):
 #   Column    Non-Null Count  Dtype
---  ------    --------------  -----
 0   ipk       17 non-null     int64
 1   bea_lain  17 non-null     int64
 2   sktm      17 non-null     int64
 3   hafalan   17 non-null     int64
 4   prestasi  17 non-null     int64
 5   status    17 non-null     int64
dtypes: int64(6)
memory usage: 944.0 bytes


In [18]:
x = bea_tahfidz.drop(["status"], axis = 1)
x.head()

ipk  bea_lain  sktm  hafalan  prestasi
0    1         0     1        1         1
1    1         0     0        1         0
2    1         0     0        2         1
3    1         0     0        2         1
4    1         0     0        2         1

In [20]:
y = bea_tahfidz["status"]
y.head()

0    1
1    1
2    1
3    1
4    1
Name: status, dtype: int64

In [76]:
from sklearn.model_selection import train_test_split

In [78]:
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size = 0.2, random_state = 123)

In [28]:
# Import Gaussian Naive Bayes model
from sklearn.naive_bayes import GaussianNB

In [29]:
# Mengaktifkan/memanggil/membuat fungsi klasifikasi Naive bayes
modelnb = GaussianNB()

In [30]:
# Memasukkan data training pada fungsi klasifikasi naive bayes
nbtrain = modelnb.fit(x_train, y_train)

In [31]:
nbtrain.class_count_

array([5., 8.])

In [32]:
# Menentukan hasil prediksi dari x_test
y_pred = nbtrain.predict(x_test)
y_pred

array([1, 1, 1, 1], dtype=int64)

In [34]:
# import confusion_matrix model
from sklearn.metrics import confusion_matrix
confusion_matrix(y_test, y_pred)

array([[0, 1],
       [0, 3]], dtype=int64)

In [53]:
# Menghitung nilai akurasi dari klasifikasi naive bayes 
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           0       0.00      0.00      0.00         1
           1       0.75      1.00      0.86         3

    accuracy                           0.75         4
   macro avg       0.38      0.50      0.43         4
weighted avg       0.56      0.75      0.64         4



c:\users\hafiz\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\hafiz\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
c:\users\hafiz\appdata\local\programs\python\python38\lib\site-packages\sklearn\metrics\_classification.py:1245: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, mo

In [86]:
# cek sample
path_test = 'bea-tahfidz-test.xlsx'
bea_tahfidz_test = pd.read_excel(path_test)

In [87]:
result = nbtrain.predict(bea_tahfidz_test)

In [88]:
result

array([1], dtype=int64)